/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118552-g99e2af4e78-20250227"
#endif /* AVUTIL_FFVERSION_H */
